Completed Week 2: Basic portfolio website
carolksun/step pull request #2
Opened 2020-06-19 22:32 UTC by carolksun

I finished creating a static html website to highlight my portfolio, following the instructions outlined in the provided github. My website includes multiple pages, such as an about me, background, photos, and a contact me page.

I have yet to deploy the website since I am waiting for the GCP billing to be set up.

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/style.css
> +.container{
For consistency there should be a space before `{`. Same in similar places from below.

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/script.js
> +      ['I\'ve lived in LA my whole life', 'I have surpassed level 3000 on Candy Crush Saga', 'I have an older sister', 'My favorite fruit is watermelon'];
Having each string on a separate line would make this easier to read. You can also avoid having the `\'` by using double quotes (this file seems to use both single quotes and double quotes for strings).

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/script.js
> +function setupTabs (){
Space between `()` and `{`.

Would be good to add a function comment to indicate what this function is doing.

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/script.js
> +    tabsContainer.querySelector(".tabs__sidebar .tabs__button").click();
It's not obvious why this code is not part of the `setupTabs`. A function comment would help.

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/index.html
> +            Los Angeles area and I like to cook and garden in my free time!</p>
Is this indentation intentional?

2020-06-23 22:00 UTC, razvanm commented on portfolio/src/main/webapp/contact.html
> +      <div class = "menu">
It looks unusual to have spaces around `=`. It's good to be consistent.

2020-06-24 00:12 UTC, carolksun commented on portfolio/src/main/webapp/script.js
> +function setupTabs (){
I deleted the setupTabs and eventListener because it was part of a previous feature that I no longer use. But I'll take note of commenting functions!

2020-06-24 00:15 UTC, carolksun commented on portfolio/src/main/webapp/index.html
> +            Los Angeles area and I like to cook and garden in my free time!</p>
oops! I fixed the indentation

2020-06-24 00:22 UTC, carolksun commented
I fixed all the comments you left! In my next PR, I'll try to be more careful with my spacing.

2020-06-24 00:38 UTC, yinggao requested changes

2020-06-24 00:38 UTC, yinggao commented on portfolio/src/main/webapp/photos.html
> +      <div class = "menu">
Remove the space between '=' to be consistent.

2020-06-24 00:38 UTC, yinggao commented on portfolio/src/main/webapp/index.html
> +      <div class = "menu">
Ditto. Review the spaces around '=' to be consistent.

2020-06-24 00:38 UTC, yinggao commented on portfolio/src/main/webapp/photos.html
> +            <li class = "currentLink"> <a href="photos.html" style="color:white"> Photos </a> </li>
Same here. Remove the space between '='.

2020-06-24 00:38 UTC, yinggao commented on portfolio/src/main/webapp/background.html
> +            <li class = "currentLink"> <a href="background.html" style="color:white"> Background</a></li>
Same here, remove the spaces around '='.

2020-06-24 02:52 UTC, razvanm commented on portfolio/src/main/webapp/background.html
> +    </p>
A slightly nicer formatting:

```
  <p>
    I am a computer science major [...] <br>
    So far [...]
  </p>
```

2020-06-24 02:52 UTC, razvanm commented on portfolio/src/main/webapp/background.html
> +            <li><a href="index.html"> About Me</a></li>
Would be good to be consistent with spacing inside the `<a>` element:

- if there is not space before `</a>` then there should be no space after `<a>` either 
- if there a space after `<a>` then there should be a space before `</a>` too.

2020-06-24 02:52 UTC, razvanm commented on portfolio/src/main/webapp/contact.html
> +          <li><a href="index.html"> About Me</a></li>
The other `<li>` elements have a space inside them while this one doesn't.

2020-06-24 16:40 UTC, razvanm commented on portfolio/src/main/webapp/style.css
> +
Leaving empty lines at the top a file is unusual.

2020-06-24 16:40 UTC, razvanm commented on portfolio/src/main/webapp/background.html
> +    <p> I am a computer science major at Caltech, expecting to graduate in June 2022. <br>
This would look better if `<p>` is alone on the line. That would also make it consistent with the fact that `</p>` is alone on its line.

2020-06-24 16:40 UTC, razvanm commented on portfolio/src/main/webapp/background.html
> +      including a summer research project at the National Institutes of Health studying Multiple Sclerosis, <br>
The `I've` should be two spaces to the right to be align with the line from below.

2020-06-24 16:40 UTC, razvanm commented on portfolio/src/main/webapp/contact.html
> +    </p>
Same observation about formatting `<p>`s as in the background.html file.

2020-06-24 17:05 UTC, razvanm approved these changes
Note that the PR title is not suitable for the commit subject. I would also suggest wrapping the body for the commit message to 80-columns because it makes it look better when using command line tools.

2020-06-24 17:14 UTC, yinggao approved these changes

2020-06-24 17:21 UTC, merged